language: python
sudo: false
python:
  - "3.5"
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
